name: UPDATE THEME | (master)

on:
  push:
    branches:
      - 'master'

jobs:
  upgrade:
    runs-on: ubuntu-latest
    steps:
      - name: Update service
        run: |
          curl -X POST ${{ secrets.THEME_UPGRADER_MASTER_WEBHOOK }}
